version: 2
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
    branches:
      only:
        - hakyll
    steps:
      - checkout
      - restore_cache:
          # 依存関係キャッシュについては https://circleci.com/docs/ja/2.0/caching/ をお読みください
          name: キャッシュされた依存関係を復元
          keys:
            - cci-demo-haskell-v1-{{ checksum "hakyll-for-github-pages.cabal" }}-{{ checksum "stack.yaml" }}
      - run:
          name: 依存関係を解決・更新
          command: |
            stack setup
            stack build --only-dependencies
      - save_cache:
          name: 依存関係をキャッシュ
          key: cci-demo-haskell-v1-{{ checksum "hakyll-for-github-pages.cabal" }}-{{ checksum "stack.yaml" }}
          paths:
            - "/root/.stack"
            - ".stack-work"
      - run:
          name: サイトの構築
          command: |
            git submodule init
            git submodule update
            cd _site/ && git checkout master
            stack build
            stack exec site build
      - run:
          name: サイトの更新
          command: |
             git config --global user.email circleci@circleci
             git config --global user.name CircleCI
             cd _site/ && git status
             cd _site/ && git add --all
             cd _site/ && git commit -m "Update (`date '+%F %T %Z'`) [ci skip]"
             cd _site/ && git push origin master
             git status
             git add _site/
             git commit -m "Update _site (`date '+%F %T %Z'`) [ci skip]"
             git push origin hakyll


