version: 2
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
    branches:
      only:
        - hakyll
    steps:
      - checkout
      - restore_cache:
          # 依存関係キャッシュについては https://circleci.com/docs/ja/2.0/caching/ をお読みください
          name: キャッシュされた依存関係を復元
          keys:
            - cci-demo-haskell-v1-{{ checksum "hakyll-for-github-pages.cabal" }}-{{ checksum "stack.yaml" }}
      - run:
          name: 依存関係を解決・更新
          command: |
            stack setup
            stack build --only-dependencies
      - save_cache:
          name: 依存関係をキャッシュ
          key: cci-demo-haskell-v1-{{ checksum "hakyll-for-github-pages.cabal" }}-{{ checksum "stack.yaml" }}
          paths:
            - "/root/.stack"
            - ".stack-work"
#      - run:
#          name: Configure SSH agent
#          command: |
#            ssh-add -D
#            ssh-add ~/.ssh/id_rsa_somefingerprint
      - run:
          name: sshのインストール
          command: |
            apt-get update
            apt-get -y install ssh
#            ssh -o "StrictHostKeyChecking=no"
#            systemctl start sshd
      - run:
          name: ssh configの設定
          command: |
            mkdir ~/.ssh
            chmod 700 ~/.ssh
            touch ~/.ssh/config
            echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

      - add_ssh_keys:
          fingerprints:
            - "07:37:8e:87:6d:0b:23:a3:87:0d:dd:8a:ed:bb:3b:6d"
            - "a6:29:7d:c9:a3:4e:ac:c4:f7:3b:06:65:09:57:f4:db"
      - run:
          name: submoduleの設定１
          command: |
            git submodule update -i --recursive

      - run:
          name: submoduleの設定２
          command: |
            cd ./_site/ && git checkout master && cd ../
      - run:
          name: サイトの構築
          command: |
            ls -a
            stack build
            stack exec site build
      - run:
          name: サイトの更新
          command: |
             git config --global user.email circleci@circleci
             git config --global user.name CircleCI
             cd _site/ && git status
             git add --all
             git commit -m "Update (`date '+%F %T %Z'`) [ci skip]"
             git push origin master
             cd ..
             git status
             git add _site/
             git commit -m "Update _site (`date '+%F %T %Z'`) [ci skip]"
             git push origin hakyll


